# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build angular app and push image to dockerhub

on:
  push:    
    tags:
      - 'v*'  
jobs:
  build:
    name: Push image to Dockerhub
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [15.x]
    steps:
    - uses: actions/checkout@v2
    - name: Get the version
      id: get_version
      run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run ci-test
    - run: npm run ci-build
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Docker build image
      run: docker build . -t ${{ secrets.DOCKERHUB_USERNAME }}/angular-material-and-flex-layout-app:${{ steps.get_version.outputs.VERSION }}
    - name: Docker push image
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/angular-material-and-flex-layout-app:${{ steps.get_version.outputs.VERSION }}